src/cpplexer/re2clex/cpp_re.cpp
There already seems to be an assertion in place that s->error_proc
cannot be NULL. There are also various other parts of code that call
into this function without checking for NULL first.
The intent of this change is that it makes this code build with
Nuxi CloudABI[1]. CloudABI is a sandboxed runtime computing environment.
As it is mainly oriented towards running (networked) services, it does
not understand the concept of stdin and stdout.
[1] Nuxi CloudABI: https://github.com/NuxiNL/cloudlibc
=> Remove dead code. Don't call into printf().

tool/build/Jamfile.v2
You should be able to tell the wave tool to build its libraries and/or executable outside of the Boost tree using the --libdir and/or --bindir command line options. The current build jamfile hardcodes the final lib and exe directory within the Boost tree. This fix allows the end-user to change that if he so desires.
=> Honor --bindir and --libdir options if present when building wave.

include/boost/wave/wave_config.hpp
Macro repetition must be avoided to prevent clash with the other libraries.
A clash example is [here](https://github.com/Arash-codedev/Simple-Web-Server/blob/master/http_examples.cpp#L5)
=> Preventing macro repetition.

include/boost/wave/util/cpp_iterator.hpp
`lex_token::get_value` assumes that `lex_token::data` is not NULL. When it
is NULL it causes UB detectable by clang's AddressSanitizer:
cpp_lex_token.hpp:242:57: runtime error: member call on null pointer of
type `boost::wave::cpplexer::impl::token_data...`
Another way to fix this - return default-constructed lex_token::string_type, but lex_token::get_value returns it by reference, so it has to be stored somewhere.
=> Don't try to access act_token when it is not valid

include/boost/wave/language_support.hpp, include/boost/wave/util/cpp_iterator.hpp, test/testwave/testfiles/t_7_001.cpp, test/testwave/testwave_app.cpp, tool/cpp.cpp
Remove the warning about the missing new line at the end of the source files in C++11 mode, as it is no longer expected.
This is required to process some of the libcxx headers (and a number of other C++11 and above headers) with Wave without warnings.
=> feature/no new line warning in c++11

samples/waveidl/idl.cpp
There was a missing parameter, as a result it was not possible to redirect stdout to a file.
=> Fix missing parameter

test/Jamfile
This adds a `Jamfile` in `test` as `wave` is the only library for which `b2 libs/libname/test` doesn't work. This would allow the elimination of the special case at https://github.com/boostorg/boost/blob/master/status/Jamfile.v2#L199.
=> Add test/Jamfile

include/boost/wave/cpplexer/re2clex/cpp_re.hpp
MSVC's standard library has checked iterators which flagged that we compare default-initialized iterators against regular iterators, which is not allowed by the standard.  The purpose of those comparisons is to ensure the iterators (formerly strictly pointers) are initialized before dereferencing them.
As it turns out, a constructor was added to the Scanner class as part of the changes that introduced this problem, and so the iterators will always be initialized, and we can remove these checks.
=> Remove comparisons vs. default-initialized (and thus singular) iterators

include/boost/wave/util/filesystem_compatibility.hpp
Wave calls `boost::filesystem::normalize()`, which unfortunately can switch to forward slashes for the first (root) component of the path. Path objects have a method `make_preferred()` to force the use of the platform's preferred dividers - backslash, in the case of Windows.  This makes the unit test output comparisons pass (in particular, the three that were failing in MSVC builds).
=> Force normalized paths to use platform path dividers

include/boost/wave/cpplexer/re2clex/aq.hpp, include/boost/wave/cpplexer/re2clex/cpp_re.hpp
In the forward iterator PR a number of functions became function templates and so moved into .hpp files. As a result some symbols were not locally visible to their users anymore, and now need to be exported for MSVC builds.
=> Resolve link errors in MSVC builds by exporting symbols

include/boost/wave/util/cpp_iterator.hpp, include/boost/wave/util/cpp_macromap.hpp
Wave uses the "%zd" format spec in a couple of places.  Unfortunately, the "z" modifier was introduced in C+11 and so it does not work with old versions of MSVC.  This commit replaces `sprintf` with `boost::lexical_cast`.
=> Fixing cpp11 format specs

include/boost/wave/cpplexer/re2clex/cpp_re.hpp
Wrong `T_DIVIDE` is bootlegged. Let's undefine it similar to https://github.com/boostorg/wave/blob/6ca4f8229d1128392b2b27c829b12af5b5f3387c/include/boost/wave/token_ids.hpp#L30-L32
```
In file included from libs/wave/src/instantiate_re2c_lexer.cpp:29:
In file included from ./boost/wave/cpplexer/re2clex/cpp_re2c_lexer.hpp:25:
In file included from ./boost/spirit/include/classic_core.hpp:11:
In file included from ./boost/spirit/home/classic/core.hpp:42:
In file included from ./boost/spirit/home/classic/core/non_terminal/grammar.hpp:21:
In file included from ./boost/spirit/home/classic/core/non_terminal/impl/grammar.ipp:15:
In file included from ./boost/spirit/home/classic/core/non_terminal/impl/object_with_id.ipp:14:
In file included from ./boost/shared_ptr.hpp:17:
In file included from …
```
=> Unbreak build on FreeBSD after e941cb580649

include/boost/wave/util/cpp_iterator.hpp
boost/wave/util/cpp_iterator.hpp(815): warning C4267: '+=': conversion from 'size_t' to 'unsigned int', possible loss of data
=> util/cpp_iterator.hpp: Fixed conversion warning

include/boost/wave/util/cpp_macromap.hpp
boost/wave/util/cpp_macromap.hpp:586:69: warning: typedef 'iterator_type' locally defined but not used [-Wunused-local-typedefs]
=> util/cpp_macromap.hpp: Fixed unused local typedef warning

samples/cpp_tokens/slex/lexer.hpp
The macro `BOOST_NO_AUTO_PTR` is defined on systems where both `auto_ptr` and
`unique_ptr` are available (and `auto_ptr` usage produces a deprecation warning).
By using `BOOST_NO_CXX11_SMART_PTR` we will favor `unique_ptr` over `auto_ptr`.
```
slex/lexer.hpp:2423:13: error: 'template<class> class std::auto_ptr' is deprecated [-Werror=deprecated-declarations]
```
=> Fixed usage of auto_ptr on systems where it is deprecated

test/testwave/testfiles/t_9_025.cpp, test/testwave/testfiles/t_9_026.cpp, test/testwave/testfiles/test.cfg
The failures t_9_025 and t_9_026 were caused by me using backslashes in the expected results. By using forward slashes the result check should work on all systems.  The failures of t_9_027 and t_9_028 are system-specific -- we cannot expect these tests to fail on systems that already use UTF-8 for path encoding. To be honest, these tests were just a check for me that the new /U yes path imbue switch was just local to a single test and didn't mess up other tests and they can be used for demonstration purposes that you have to switch to UTF8 path conversions on Windows. t_9_025 and t_9_026 alone are able to show that you can now open includes with UTF-8 encoded paths on all systems. I think t_9_027 and t_9_028 can be left out of the full test suite so i disabled  them in test.cfg.
=> fix utf8 testcases on non-windows systems

include/boost/wave/cpplexer/re2clex/cpp_re2c_lexer.hpp, src/instantiate_cpp_exprgrammar.cpp, src/instantiate_cpp_grammar.cpp, src/instantiate_cpp_literalgrs.cpp, src/instantiate_defined_grammar.cpp, src/instantiate_predef_macros.cpp, src/instantiate_re2c_lexer.cpp, src/instantiate_re2c_lexer_str.cpp, test/build/Jamfile.v2, test/testwave/quick.cpp
=> Add BOOST_SYMBOL_VISIBLE to explicit instantiations, to fix link errors on Linux/Mac

include/boost/wave/util/flex_string.hpp
MSVC emits warning 4458 about the local typedef "pointer" shadowing the class member typedef "pointer". This fix renames the local typedef to "value_pointer" to eliminate the warning.
=> Rename typedef "pointer" to fix MSVC warning 4458

samples/list_includes/instantiate_lexertl_lexer.cpp, samples/real_positions/instantiate_re2c_lexer.cpp
Two samples fail at the link stage looking for a different `new_lexer_gen<>::new_lexer()` than we provide.
AFAICT the type of the lexer is dependent on what string was used to construct the wave context object and that propagates down. Updating these files fixes the error.
=> Instantiate lexers with std::string, not flex_string

samples/advanced_hooks/build/Jamfile.v2, samples/custom_directives/build/Jamfile.v2, samples/emit_custom_line_directives/build/Jamfile.v2, samples/quick_start/build/Jamfile.v2
I noticed several samples would fail at the link stage, all with missing Boost.Filesystem symbols. I couldn't find a way to have them inlined so I assume this changed at some point. Adding FS explicitly fixes it.
=> Link against Boost.Filesystem to resolve missing symbols in samples

include/boost/wave/cpplexer/re2clex/cpp_re2c_lexer.hpp, samples/cpp_tokens/slex/cpp_slex_lexer.hpp, samples/list_includes/lexertl/lexertl_lexer.hpp
It applies the same fix suggested by the original poster of #54 and if merged will resolve it.
=> Fix the problem where disabling `include_next` support breaks regular `include`.

samples/waveidl/idllexer/idl_lex_iterator.hpp, samples/waveidl/idllexer/idl_re2c_lexer.hpp
- use the idllexer generator instead of the cpp one
- eliminate a double free encountered during fix
If merged, this will resolve #56
=> Restore waveidl sample to working condition

include/boost/wave/util/flex_string.hpp
This PR fixes the compilation problem caused by the removal of some member typdef in std::allocator since C++20 standard.
```
In file included from ./boost/wave/wave_config.hpp:230,
from libs/wave/src/instantiate_cpp_exprgrammar.cpp:14:
./boost/wave/util/flex_string.hpp: In instantiation of ‘class boost::wave::util::CowString<boost::wave::util::AllocatorStringStorage<char> >’:
./boost/wave/util/flex_string.hpp:1417:7:   required from ‘class boost::wave::util::flex_string<char, std::char_traits<char>, std::allocator<char>, boost::wave::util::CowString<boost::wave::util::AllocatorStringStorage<char> > >’
./boost/wave/util/file_position.hpp:85:17:   required from ‘struct boost::wave::util::file_position<boost::wave::util::flex_string<char, std::char_traits<char>, std::allocator<char>, …
```
=> Fix compilation issue caused by std::allocator member removal in C++20

samples/token_statistics/collect_token_statistics.hpp, samples/token_statistics/instantiate_xlex_lexer.cpp, samples/token_statistics/xlex/xlex_lexer.hpp, test/build/Jamfile.v2, test/testlexers/test_xlex_lexer.cpp
Fix xlex and the token_statistics sample by:
- Changing space handling to match lexertl so lexer test passes
- Adding xlex to test Jamfile
- Adding remedial line/column tracking to xlex (positions were often reported as 0:-1)
- Fixing token_statistics id index for counting
=> Repair xlex and add to test suite

build/Jamfile.v2, samples/advanced_hooks/build/Jamfile.v2, samples/cpp_tokens/build/Jamfile.v2, samples/custom_directives/build/Jamfile.v2, samples/emit_custom_line_directives/build/Jamfile.v2, samples/hannibal/build/Jamfile.v2, samples/lexed_tokens/build/Jamfile.v2, samples/list_includes/build/Jamfile.v2, samples/preprocess_pragma_output/build/Jamfile.v2, samples/quick_start/build/Jamfile.v2, samples/real_positions/build/Jamfile.v2, samples/token_statistics/build/Jamfile.v2, samples/waveidl/build/Jamfile.v2, test/build/Jamfile.v2, tool/build/Jamfile.v2
Boost develop branch has an updated date_time that is header-only so
Wave's builds will now fail unless this dependency is removed.
=> Remove linking to newly header-only date_time

samples/token_statistics/xlex/xpressive_lexer.hpp
The header is deprecated in favor of `<iterator>`. It generates compiler warnings and will be removed in a future release.
Also, added a missing include for `iterator_value` trait.
=> Remove use of deprecated header boost/detail/iterator.hpp

include/boost/wave/cpplexer/re2clex/cpp_re.hpp, samples/cpp_tokens/cpp_tokens.cpp, samples/cpp_tokens/cpp_tokens.hpp, samples/cpp_tokens/slex/lexer.hpp, samples/cpp_tokens/slex_iterator.hpp, samples/hannibal/translation_unit_parser.h, samples/lexed_tokens/lexed_tokens.cpp, samples/list_includes/list_includes.cpp, samples/list_includes/list_includes.hpp, samples/token_statistics/collect_token_statistics.hpp, samples/token_statistics/token_statistics.cpp, samples/token_statistics/token_statistics.hpp, samples/token_statistics/xlex_iterator.hpp, samples/waveidl/idl.cpp, samples/waveidl/idl.hpp, samples/waveidl/idllexer/idl_lex_iterator.hpp, samples/waveidl/idllexer/idl_re.cpp, samples/waveidl/idllexer/idl_re.hpp, src/cpplexer/re2clex/cpp_re.cpp, src/wave_config_constant.cpp, test/testlexers/test_lexertl_lexer.cpp, test/testlexers/test_re2c_lexer.cpp, test/testlexers/test_slex_lexer.cpp, test/testlexers/test_xlex_lexer.cpp, test/testwave/testwave_app.cpp, tool/cpp.cpp, tool/cpp.hpp
Reduce build time by:
- using iosfwd instead of iostream, where possible
- where iostream is necessary but only used for debugging,
making its inclusion conditional
- removing old C-style headers
I used IWYU to guide this work
=> Remove unused headers

doc/samples.html, samples/Jamfile.v2, samples/check_macro_naming/build/Jamfile.v2, samples/check_macro_naming/check_macro_naming.cpp, samples/check_macro_naming/check_macro_naming.hpp
This has a direct use in Boost's own QA checks and demonstrates the use of macro definition and include guard callbacks, as well as Boost.Filesystem.
=> Introduce a new sample that checks macro naming conventions

ChangeLog
This is a high-level view of the changes currently sitting in develop vs. master
=> Log initial set of changes for 1.74

ChangeLog, doc/class_ref_ctxpolicy_depr.html, doc/compiletime_config.html, include/boost/wave/wave_config.hpp
Targeting a one year transition period for C++03 -> C++11, and one release less to finally get off the old hooks - assuming there are even any users of them.
=> Deprecate C++03 and re-deprecate the old preprocessor hooks

include/boost/wave/cpplexer/cpp_lex_token.hpp, include/boost/wave/util/cpp_macromap.hpp, samples/cpp_tokens/slex_token.hpp, samples/real_positions/real_position_token.hpp, test/testwave/testfiles/t_5_036.cpp, test/testwave/testfiles/t_5_036.hpp, test/testwave/testfiles/t_5_037.cpp, test/testwave/testfiles/test.cfg
An (optional) extra position field is added to token_data and set for
any identifier token created from a macro expansion. This information
is used to correctly calculate the filename and line number.
If merged, this will resolve #94.
NOT intended for Boost 1.74.
=> Track the location tokens were expanded from, for __LINE__ and __FILE__

include/boost/wave/wave_config.hpp
Thanks to Jeff Trull for the catch.
=> Remove use of non-existent Boost.Config macro BOOST_NO_CXX11_HDR_MEMORY

samples/preprocess_pragma_output/preprocess_pragma_output.hpp
Clang warns that a for loop in a sample increments an iterator in both
the header and the body. This seems to be done on purpose to skip
whitespace. I used std::advance in the header instead, for clarity.
Also cleaned up an unused type in the same file while I was there.
If merged, this will resolve #90
=> Clarify loop logic to satisfy a Clang warning

doc/class_reference_ctxpolicy.html, doc/samples.html
* Add documentation for three undocumented hooks
Those are found_unknown_directive, emit_line_directive, and locate_include_file
Also tweak formatting, fix typos.
* Add documentation for five samples
* Add links from samples docs to the hooks they use
=> Additional documentation

.drone.star, .github/workflows/ci.yml, .travis.yml, ChangeLog, appveyor.yml, include/boost/wave/wave_config.hpp
This removes only support for C++98/03 as a compiler for this library - Wave continues to support C++98 and C++03 constructs as a preprocessor.
Support for C++98 and C++03 compilers was deprecated in 1.74, with a warning message.
Doing this enables the use of C++11 constructs in the code, which should help maintainability.
=> Remove support for C++03 and prior compilers

include/boost/wave/util/cpp_iterator.hpp, test/build/Jamfile.v2, test/testwave/default_hooks.cpp
At some point in the past the handling for `#if` and `#ifdef` diverged. The code that handles emitting a line directive when a conditional section is skipped worked for `#if` but not `#ifdef/#ifndef`.
This problem was not observable when the `eat_whitespace_hooks` were used instead of the `default_preprocessing_hooks`, because the former signals skipped newlines through the `may_skip_whitespace` hook, hiding the problem. Furthermore, the majority of Wave tests use the
`eat_whitespace` hooks, so it wasn't visible in testing.
This change restores `#ifdef/#ifndef` to the same section as `#if`, so any future changes to conditional handling will happen uniformly. Also, a test case is added to cover the default hooks and this particular case.
If merged, this will resolve #138
=> Fix line directives for ifdef and ifndef when default hooks are used

include/boost/wave/util/cpp_iterator.hpp, test/testwave/testfiles/t_2_031.cpp, test/testwave/testfiles/test.cfg
In C++11 and later modes Wave by default does not require newline prior to EOF. This works fine but
there is one place where the test for this feature was used where Wave is not necessarily looking at the end of the file: `pp_is_last_on_line`. One observable (and surprising) result is that unknown
directives are not getting flagged - but there may be others. The unit tests did not discover this
problem because they generally do not set c++11 mode.
This PR adds the necessary qualifiers and adds a unit test (the same as an existing one but with
C++11 enabled).
If merged this will resolve #137
=> Qualify "newline at EOF not required" with actually being there

doc/class_reference_context.html
It currently says Wave "will now" report an error for input which is not terminated by a newline. In fact it "will not" do that.
I also made some descriptive edits that made sense to me personally.
=> Clarify the purpose of the single_line language option

include/boost/wave/util/cpp_macromap_predef.hpp, include/boost/wave/util/flex_string.hpp, samples/emit_custom_line_directives/emit_custom_line_directives.hpp, tool/stop_watch.hpp
There have been compiler warnings about `sprintf` usage for some time, and now we have a bug report as well (#145). I replaced them mostly with `boost::format` but in one case with `std::to_string` (our second use of a C++11 feature!).
I also did a few cleanups while I was in the code - indentation and one unused header.
=> Clean up sprintf usage

include/boost/wave/grammars/cpp_chlit_grammar.hpp, include/boost/wave/grammars/cpp_intlit_grammar.hpp, include/boost/wave/token_ids.hpp, tool/trace_macro_expansion.hpp
Address the following issues:
1. comma operator inside square brackets (used in Phoenix expressions) is deprecated as of C++20
2. different typed enums need some extra help to be "interoperable" (for arithmetic)
3. Replace `tmpnam` calls with safer Boost.Filesystem features
These are flagged by Clang (1 and 2) or the linker (3).
Merging this PR will resolve #135 and #147
=> Fix various warnings

appveyor.yml, tool/trace_macro_expansion.hpp
VC++ builds fail on this due to the use of wchar_t
=> Use portable filesystem string conversion instead of native()

README.md, appveyor.yml, include/boost/wave/util/cpp_macromap.hpp, include/boost/wave/util/cpp_macromap_predef.hpp, include/boost/wave/util/iteration_context.hpp, samples/list_includes/lexertl/lexertl_lexer.hpp, tool/trace_macro_expansion.hpp
1. Remove some additional calls to sprintf() via Boost.Format and std::to_string to silence warnings
2. Remove Appveyor C++03 configurations
3. Update build "badge" to reflect Github Actions and Appveyor, instead of Travis (now unused)
=> MSVC-related cleanups

ChangeLog
The 1.79 release window is approaching. I don't know whether we'll get anything else done in time for code freeze but I've updated the ChangeLog to reflect the latest activity. A merge of develop into master will follow.
=> Update ChangeLog for 1.79 bugfixes

appveyor.yml, build/Jamfile.v2
This is required as of https://github.com/boostorg/wave/blob/develop/build/Jamfile.v2#L15
Add a VS2013 job which would otherwise fail, see #153
Note that VS2013 is NOT supported by Boost.Wave anymore due to incomplete C++11 support. The added requirement makes it skip building Boost.Wave on that (and possibly other affected) compiler(s) avoiding a hard error.
=> Add C++11 constexpr requirement

meta/libraries.json
See the similar commits from @eldiener, e.g. https://github.com/boostorg/nowide/commit/de9a58d43b9d4bd9b6eae5e69a6da391dadfa625
=> Add "cxxstd" json field to the meta json file.

test/build/Jamfile.v2
Followup to https://github.com/boostorg/wave/pull/154
I hope I got this right, doesn't Appveyor run for PRs too?
I was also a bit confused about the "build" subfolder of test which I've seen here for the first time. Wouldn't it be easier to put that into `test/Jamfile` and get rid of the `test/build` folder?
Anyway, check if this makes sense and passes on the updated Appveyor config or if there need to be similar checks elsewhere
=> Add the C++11 requirements also to the test project

include/boost/wave/wave_config.hpp, samples/Jamfile.v2
- Test the requirement of "constexpr" for the deprecation error
- Ensure C++11 requirements are checked for the samples build
As @Flamefire noticed, subprojects like "test" and "samples" also need C++11 requirements for their builds to pass (or more accurately, not happen) with C++03 compilers. This adds those requirements for the samples.
This also adds an explicit check on the availability of `constexpr` to the existing deprecation error, so the problem will be more obvious when someone attempts a manual build. It turns out that msvc-12 supports many parts of C++11 but not that one. Going forward we will need to update the check as we use additional C++11 features.
=> Clean up C++11 requirements further

include/boost/wave/util/flex_string.hpp
This PR makes 3 commits:
- Convert all checks for whether `pData_` points to `emptyString_` to checks for zero `capacity()`. This is a safer check, which should work across shared library boundaries.
- Added compile-time asserts that `pData_` never points to `emptyString_` when `capacity()` is zero. This fixes https://github.com/boostorg/wave/issues/159.
- Removes `AllocatorStringStorage::Realloc`. This function was not used and potentially incorrect, as it would call `Free` on the input buffer, even if it was `emptyString_`.
I did not use `#pragma` to silence the warnings because it seems gcc 11.2 doesn't support disabling this warning (the warnings are still emitted).
=> Fix warnings about freeing non-heap-allocated object

include/boost/wave/grammars/cpp_expression_grammar.hpp, test/testwave/testfiles/t_5_038.cpp, test/testwave/testfiles/test.cfg
It seems that the grammar for conditional preprocessor expressions was not updated when long integer literals were added for C++11. This seems to work most of the time, as they get recognized as `PP_NUMBER` tokens, which are in the grammar. Sometimes, though, when they are produced as part of a macro expansion, they can appear as `LONGINTLIT` tokens, which are _not_ in the grammar. Wave then rejects the expression as invalid.
These changes add `LONGINTLIT` tokens as valid numbers in expressions, and in doing so resolve #162
=> Let expanded long integer literals participate in conditional expressions

samples/cpp_tokens/slex/cpp_slex_lexer.hpp, samples/list_includes/lexertl/lexertl_lexer.hpp, samples/token_statistics/xlex/xlex_lexer.hpp
Under Visual Studio 2019 (and possibly earlier), building with `/permissive-` causes three samples to fail to compile. Adding the
`/Zc:twoPhase-` option makes them compile successfully again. See bug #160 for more details.
It's unclear what the source of this issue is, but using `constexpr` variables instead of a macro is better practice anyway, and fixes the errors.
=> Use constexpr instead of macros for tokenid constants in samples

ChangeLog, include/boost/wave/util/cpp_iterator.hpp, test/testwave/testfiles/t_5_039.cpp, test/testwave/testfiles/test.cfg
The initial part of a conditional block (the if/ifdef/ifndef) takes the "slow" path through the code in cpp_iterator.hpp using the C++ expression grammar, while else and endif directives take the "fast" path. The slow path sets must_emit_line_directive, and it will be cleared after either else or endif is processed. Unfortunately when an else precedes the endif, must_emit_line_directive is cleared and is never set, as only the slow path sets it. The result is proper line directives are issued for the else clause, but not for the subsequent endif.
This change adds setting of must_emit_line_directive in the "fast" path for endif so line directives are considered after an intervening else. It also adds extensive unit tests for line directives.
If merged, this will resolve #24
=> Fix line directives after endif following else

ChangeLog, include/boost/wave/util/cpp_iterator.hpp, test/testwave/testfiles/t_5_039.cpp, test/testwave/testfiles/test.cfg
* Fix line directives after endif when else clause is present
The initial part of a conditional block (the if/ifdef/ifndef) takes
the "slow" path through the code in cpp_iterator.hpp using the C++
expression grammar, while else and endif directives take the "fast"
path. The slow path sets must_emit_line_directive, and it will be
cleared after either else or endif is processed. Unfortunately when
an else precedes the endif, must_emit_line_directive is cleared and is
never set, as only the slow path sets it. The result is proper line
directives are issued for the else clause, but not for the subsequent
endif.
This changes adds setting of must_emit_line_directive in the "fast"
path for endif so line directives are considered after an intervening else.
=> Fix line directives after endif following else (#170)

include/boost/wave/util/flex_string.hpp
Since direct call to `a.max_size()` may fail to compile since C++11.
I found the fix was missing for `SmallStringOpt` when building a project at work in C++20 mode (where `std::allocator`'s `max_size` is removed).
Related to #85, #86, #93.
=> Use `boost::allocator_max_size` for `SmallStringOpt` to obtain allocator's max size

test/testwave/testfiles/t_5_034.cpp
I somehow managed to miss this in my last commit. This test verifies that \e and \E can be used in preprocessor conditional expressions.
=> Add test for \e \E escape sequences overlooked in prior commit

include/boost/wave/cpplexer/re2clex/cpp_re.hpp
boost::wave sometimes calls memmove with a nullptr destination and a 0 byte length. This is undefined behavior. This diff adds a check so that memmove is not called if the length is 0
=> Fix UB in memmove

include/boost/wave/util/cpp_iterator.hpp, test/testwave/testfiles/t_2_006.cpp
This approach differs from the initial plan - which just returned when an empty pragma was detected - because we still need to fire pragma hooks.
=> Support a single #pragma without body

include/boost/wave/util/filesystem_compatibility.hpp
This will be for Boost 1.84 forward. The new replacements were available previously, so for some versions before 1.84 we'll still see deprecation warnings if users mix versions of Boost and Wave.
In the meantime the builds will get quieter.
=> Replace deprecated boost::filesystem methods with their new names

include/boost/wave/util/filesystem_compatibility.hpp, samples/check_macro_naming/check_macro_naming.cpp, samples/waveidl/idl.cpp, tool/cpp.cpp, tool/trace_macro_expansion.hpp
Boost.Filesystem just made some changes in its develop branch (one header and two methods removed) and as a result,  Wave is failing CI in develop. This PR makes appropriate adjustments.
=> Handle some previously deprecated, now removed, filesystem code

include/boost/wave/cpplexer/re2clex/cpp_re2c_lexer.hpp
There is no guarantee (indeed, it is unlikely) that data within the scanner buffer will be null terminated and so the constructor that accepts a pointer and a count is appropriate.
This is one of the issues revealed by the `BOOST_WAVE_BSIZE` variation experiment
=> Use correct string constructor for non-null-terminated range

include/boost/wave/cpplexer/re2clex/cpp_re.hpp
Experiments with `BOOST_WAVE_BSIZE` revealed that we were missing some backslash+newline cases, and in others, testing invalid memory locations for the presence of a newline.
These fixes repair the specific issues found but a more general solution is probably in order (and will be particularly needed given the more lenient treatment of newline escapes in C++23)
=> Fixes for escaped newline handling

include/boost/wave/cpplexer/re2clex/cpp_re.hpp, test/build/Jamfile.v2, test/testwave/fill_boundary.cpp
I think this change is in line with how s->ptr and marker are expected to interact.
This is in reference to:
https://github.com/boostorg/wave/issues/202
=> Update marker before and after fill() operation in cpplexer

.github/workflows/ci.yml, ChangeLog, appveyor.yml, include/boost/wave/cpplexer/re2clex/cpp_re.hpp, include/boost/wave/cpplexer/re2clex/cpp_re2c_lexer.hpp, include/boost/wave/util/cpp_iterator.hpp, include/boost/wave/util/filesystem_compatibility.hpp, samples/check_macro_naming/check_macro_naming.cpp, samples/waveidl/idl.cpp, test/build/Jamfile.v2, test/testwave/fill_boundary.cpp, test/testwave/testfiles/t_2_006.cpp, tool/cpp.cpp, tool/trace_macro_expansion.hpp
In this release we fix two filed bugs and some other problems: a broken CI, removed filesystem API call, and a potential vulnerability.
=> Merge 1.85 fixes

include/boost/wave/cpplexer/re2clex/cpp_re2c_lexer.hpp, samples/waveidl/idllexer/idl_re2c_lexer.hpp
For the usual security reasons. Surfaced by an MSVC warning.
=> Use vsnprintf instead of vsprintf

include/boost/wave/grammars/cpp_expression_value.hpp, test/testwave/testfiles/t_6_070.cpp, test/testwave/testfiles/test.cfg
When verifying that code being preprocessed does not invoke undefined behavior, Wave does it itself.
This change performs tests on the operands in advance, instead.
Tests `t_6_15`, `t_6_17`, and `t_6_18` (though not `t_6_17`, for some reason) signal errors in the absence of this fix with `-fsanitize=signed-integer-overflow` configured, but it does not cause the tests to fail, because these tests are expected to exit with an error anyway.
If merged, this will fix #197
=> Fix checks for signed overflow

.github/workflows/ci.yml
To test against different compiler versions we use older Docker images, which in turn have different glibc versions. Github recently deprecated Node version 16, which had been built with an older glibc version, and the newer Node version requires a glibc version that is not available on the old images, causing builds to fail.
This is a hack permitting the continued use of Node 16, until Github decides to make it impossible.
=> Use only node16 in CI

build.jam, build/Jamfile.v2, samples/Jamfile.v2, samples/check_macro_naming/check_macro_naming.cpp, samples/cpp_tokens/build/Jamfile.v2, samples/list_includes/build/Jamfile.v2, samples/token_statistics/build/Jamfile.v2, samples/waveidl/build/Jamfile.v2, test/build/Jamfile.v2, test/testlexers/test_lexertl_lexer.cpp, test/testlexers/test_slex_lexer.cpp, test/testlexers/test_xlex_lexer.cpp, tool/build/Jamfile.v2
This is part of the effort to make the Boost libraries "modular" for build and consumption. See https://lists.boost.org/Archives/boost/2024/01/255704.php and https://github.com/grafikrobot/boost-b2-modular/blob/b2-modular/README.adoc for more information.
This PR depends on the following other PRs being merged to both develop and master branches of the respective repos:
- https://github.com/boostorg/boost/pull/854
This PR will be changed to ready for review, i.e. not draft, when the above are merged. Do not merge this one until that time.
=> Add support for modular build structure.

include/boost/wave/util/cpp_macromap.hpp, test/testwave/testfiles/t_8_004.cpp
Fix #220.
Check if the variadics variable is omitted; put an empty string if so.
=> Fix empty stringify under C++20

samples/real_positions/real_position_token.hpp
`boost/detail/atomic_count.hpp` was moved to `boost/smart_ptr/detail` and the old header is deprecated and emits warnings.
=> Avoid including deprecated atomic_count.hpp header

.github/workflows/ci.yml
GitHub removes the Ubuntu 20 runners
Currently there are random intended failures (brownout phase):
> This is a scheduled Ubuntu 20.04 retirement. Ubuntu 20.04 LTS runner will be removed on 2025-04-15. 
As the Clang version doesn't seem to matter just update to the latest OS
=> GHA: Use Ubuntu 24.04 for clang test
